version: 2

models:
  - name: stg_nations
    columns:
      - name: nationid
        description: '{{ doc("prkey")}}'
        data_tests:
          - unique
          - not_null
      - name: name
        data_tests:
        - accepted_values:
            values: ['AFRICA','AMERICA','ASIA','EUROPE','MIDDLE EAST']
            config:
                store_failures: true
      - name: regionid
        description: '{{ doc("prkey")}}'
        data_tests:
          - relationships:
              to: ref('stg_regions')
              field: regionid
              config:
                store_failures: true